version: "3"

services:
  wordpress:
    image: wordpress:${WORDPRESS_VERSION}-php${PHP_VERSION}-apache
    environment:
      HTTPS_METHOD: nohttps
      VIRTUAL_HOST: wordpress
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - database
    networks:
      - front
      - back
    ports:
      - 80:80
    volumes:
      - "wp:/var/www/html:rw"
  wp-cli:
    image: wordpress:cli-php${PHP_VERSION}
    networks:
      - back
    volumes:
      - "wp:/var/www/html:rw"
  database:
    image: mariadb:${MARIADB_VERSION}
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - back
  tests:
    image: php:${PHP_VERSION}-cli
    networks:
      - front
    volumes:
      - "./tests:/tmp/tests:ro"

networks:
  front: {}
  back: {}

volumes:
  wp: {}
