version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment
          command: docker-compose up -d
      - run:
          name: Wait for WordPress to become available
          command: sleep 15
      - run:
          name: Install WordPress
          command: |
            docker-compose run --rm wp-cli wp core install \
            --title="Hello World" \
            --admin_user="wordpress" \
            --admin_password="wordpress" \
            --admin_email="admin@example.com" \
            --url="http://wordpress" \
            --skip-email
      - run:
          name: Run test suite
          command: docker-compose run --rm tests composer test
